### ISSUE TITLE
Youtube error

### ISSUE THREAD

**Issue by gcfrxbots** [wootiown/rxbot#26]
ERROR: This video is unavailable.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files\Python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\Python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 2115, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\pafy\backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "C:\Program Files\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Program Files\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Program Files\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Grant/IdeaProjects/rxbot3/Run.py", line 164, in tick
    nowplaying = srcontrol.playsong()
  File "C:\Users\Grant\IdeaProjects\rxbot3\SongRequest.py", line 168, in playsong
    yt = pafy.new(self.songkey, basic=True, size=False)
  File "C:\Program Files\Python37\lib\site-packages\pafy\pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "C:\Program Files\Python37\lib\site-packages\pafy\backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\pafy\backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "C:\Program Files\Python37\lib\site-packages\pafy\backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video is unavailable.

**Comment by gcfrxbots** [comment]
Solved, getalbumart() was just checking if the key was youtube by checking if the first digit was "T" so if the youtube key started with T then it crashed. Fixed by making it also check length.

**Comment by gcfrxbots** [comment]
Presumed issue with youtube / ytdl. Added in an error catch in playsong() to stop bot from crashing.
