### ISSUE TITLE
Typing !sr with nothing else crashes bot

### ISSUE THREAD

**Issue by gcfrxbots** [wootiown/rxbot#35]
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "Run.py", line 185, in console
    runcommand(command, cmdarguments, "CONSOLE", True)
  File "Run.py", line 106, in runcommand
    output = eval(cmd + '(' + arg1 + ', ' + arg2 + ')')
  File "<string>", line 1, in <module>
  File "C:\Users\Grant\Documents\rxbot\RxBot\SongRequest.py", line 371, in songrequest
    if validators.url(requestArgs[0]):
IndexError: list index out of range

**Comment by gcfrxbots** [comment]
Will fix in 3.5
